play_commands = ["play", "start", "resume"]
pause_commands = ["pause"]
next_song_commands = ["next", "next song"]
previous_song_commands = ["previous", "previous song"]
stop_commands = ["stop"]
volume_up_commands = ["volume up", "louder", "increase volume"]
volume_down_commands = ["volume down", "quieter", "decrease volume"]